// React/src/components/FilterForm/FilterForm.jsx
import React, {memo, useMemo} from "react";
import {Form, GroupItem, SimpleItem, Label} from "devextreme-react/form";
import {startViewDate, endViewDate} from "../../config";

const FilterForm = memo((props) => {
    const {
        onFilterValueChanged,
        onCheckboxChange,
        onStartDateChange,
        onEndDateChange,
        useDisable
    } = props;

    const filterInputOptions = useMemo(() => ({
        placeholder: 'Filter...',
        onKeyUp: onFilterValueChanged
    }), [onFilterValueChanged]);

    const checkBoxOptions = useMemo(() => ({
        value: useDisable,
        text: 'Disable appointment are not filtered',
        onValueChanged: onCheckboxChange
    }), [useDisable, onCheckboxChange]);

    const startDateOptions = useMemo(() => ({
        onValueChanged: onStartDateChange,
        type: 'date',
        value: startViewDate
    }), [onStartDateChange]);

    const endDateOptions = useMemo(() => ({
        onValueChanged: onEndDateChange,
        type: 'date',
        value: endViewDate
    }), [onEndDateChange]);

    return (
        <Form>
            <GroupItem>
                <SimpleItem
                    editorType='dxTextBox'
                    editorOptions={filterInputOptions}
                >
                    <Label text='Text'/>
                </SimpleItem>
                <SimpleItem
                    editorType='dxDateBox'
                    editorOptions={startDateOptions}
                >
                    <Label text='Start Date'/>
                </SimpleItem>
                <SimpleItem
                    editorType='dxDateBox'
                    editorOptions={endDateOptions}
                >
                    <Label text='End Date'/>
                </SimpleItem>
                <SimpleItem
                    editorType='dxCheckBox'
                    editorOptions={checkBoxOptions}
                />
            </GroupItem>
        </Form>
    )
});

export default FilterForm;

// Vue/src/components/FilterForm/FilterForm.vue
<template>
  <DxForm
      :label-mode='labelMode'
      :label-location='labelLocation'
  >
    <DxGroupItem>
      <DxSimpleItem
          editorType='dxTextBox'
          :editorOptions='filterInputOptions'
      >
        <DxLabel text='Text'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='startDateOptions'
      >
        <DxLabel text='Start Date'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='endDateOptions'
      >
        <DxLabel text='End Date'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxCheckBox'
          :editorOptions='checkBoxOptions'
      />
    </DxGroupItem>
  </DxForm>
</template>

<script>
import {DxForm, DxGroupItem, DxLabel, DxSimpleItem} from 'devextreme-vue/form';
import {endViewDate, startViewDate} from '@/config';

export default {
  name: 'FilterForm',
  props: [
    'onFilterValueChange',
    'onCheckboxChange',
    'onStartDateChange',
    'onEndDateChange',
    'useDisable'
  ],
  components: {
    DxForm,
    DxSimpleItem,
    DxGroupItem,
    DxLabel
  },
  data() {
    return {
      labelMode: 'outside',
      labelLocation: 'left',
      filterInputOptions: {
        placeholder: 'Filter...',
        onKeyUp: this.onFilterValueChange
      },
      startDateOptions: {
        value: startViewDate,
        onValueChanged: this.onStartDateChange
      },
      endDateOptions: {
        value: endViewDate,
        onValueChanged: this.onEndDateChange
      },
      checkBoxOptions: {
        value: this.useDisable,
        text: 'Disable appointment are not filtered',
        onValueChanged: this.onCheckboxChange
      }
    };
  },
};
</script>
