// Vue/src/components/FilterForm/FilterForm.vue
<script setup lang="ts">
import { ref } from 'vue';
import { DxForm, DxGroupItem, DxLabel, DxSimpleItem } from 'devextreme-vue/form';
import { type DxDateBoxTypes } from 'devextreme-vue/date-box';
import { type DxTextBoxTypes } from 'devextreme-vue/text-box';
import type { FilterValues } from './interfaces';

const emit = defineEmits<{
  (e: 'filterValuesChanged', values: FilterValues): void
}>();

const filterValues = ref({
  text: '',
  startDate: new Date(2022, 9, 1),
  endDate: new Date(2022, 9, 28),
});

const textEditorOptions = ref<DxTextBoxTypes.Properties>({
  placeholder: 'Filter...',
  valueChangeEvent: 'keyup',
  value: filterValues.value.text,
  onValueChanged: (e: DxTextBoxTypes.ValueChangedEvent) => {
    filterValues.value.text = e.value as string;
    emit('filterValuesChanged', filterValues.value);
  },
});

const startEditorOptions = ref<DxDateBoxTypes.Properties>({
  type: 'date',
  value: filterValues.value.startDate,
  onValueChanged: (e: DxDateBoxTypes.ValueChangedEvent) => {
    filterValues.value.startDate = e.value as Date;
    emit('filterValuesChanged', filterValues.value);
  },
});

const endEditorOptions = ref<DxDateBoxTypes.Properties>({
  type: 'date',
  value: filterValues.value.endDate,
  onValueChanged: (e: DxDateBoxTypes.ValueChangedEvent) => {
    filterValues.value.endDate = e.value as Date;
    emit('filterValuesChanged', filterValues.value);
  },
});
</script>
<template>
  <DxForm
    label-mode="outside"
  >
    <DxGroupItem caption="Filter Appointments">
      <DxSimpleItem
        editor-type="dxTextBox"
        :editor-options="textEditorOptions"
      >
        <DxLabel text="Text"/>
      </DxSimpleItem>
      <DxSimpleItem
        editor-type="dxDateBox"
        :editor-options="startEditorOptions"
      >
        <DxLabel text="Start Date"/>
      </DxSimpleItem>
      <DxSimpleItem
        editor-type="dxDateBox"
        :editor-options="endEditorOptions"
      >
        <DxLabel text="End Date"/>
      </DxSimpleItem>
    </DxGroupItem>
  </DxForm>
</template>

// React/src/components/FilterForm/FilterForm.tsx
import { useMemo, useState } from 'react';
import {
  Form,
  GroupItem,
  SimpleItem,
  Label,
} from 'devextreme-react/form';
import { type DateBoxTypes } from 'devextreme-react/date-box';
import { type TextBoxTypes } from 'devextreme-react/text-box';
import type { FilterFormProps } from './interfaces';

function FilterForm(props: FilterFormProps): JSX.Element {
  const [filterValues, setFilterValues] = useState({
    text: '',
    startDate: new Date(2022, 9, 1),
    endDate: new Date(2022, 9, 28),
  });

  const textEditorOptions = useMemo<TextBoxTypes.Properties>(() => ({
    placeholder: 'Filter...',
    valueChangeEvent: 'keyup',
    value: filterValues.text,
    onValueChanged: (e: TextBoxTypes.ValueChangedEvent): void => {
      const newValues = { ...filterValues, text: e.value };
      setFilterValues(newValues);
      props.filterValuesChanged(newValues);
    },
  }), [filterValues, props]);

  const startDateOptions = useMemo<DateBoxTypes.Properties>(() => ({
    type: 'date',
    value: filterValues.startDate,
    onValueChanged: (e: DateBoxTypes.ValueChangedEvent): void => {
      const newValues = { ...filterValues, startDate: e.value };
      setFilterValues(newValues);
      props.filterValuesChanged(newValues);
    },
  }), [filterValues, props]);

  const endDateOptions = useMemo<DateBoxTypes.Properties>(() => ({
    type: 'date',
    value: filterValues.endDate,
    onValueChanged: (e: DateBoxTypes.ValueChangedEvent): void => {
      const newValues = { ...filterValues, endDate: e.value };
      setFilterValues(newValues);
      props.filterValuesChanged(newValues);
    },
  }), [filterValues, props]);

  return (
    <Form labelMode='outside' className='filter-form'>
      <GroupItem caption='Filter Appointments'>
        <SimpleItem
          editorType='dxTextBox'
          editorOptions={textEditorOptions}
        >
          <Label text='Text' />
        </SimpleItem>
        <SimpleItem
          editorType='dxDateBox'
          editorOptions={startDateOptions}
        >
          <Label text='Start Date' />
        </SimpleItem>
        <SimpleItem
          editorType='dxDateBox'
          editorOptions={endDateOptions}
        >
          <Label text='End Date' />
        </SimpleItem>
      </GroupItem>
    </Form>
  );
}

export default FilterForm;
