// Vue/src/components/FilterForm/orig_FilterForm.vue
<template>
  <DxForm
      :label-mode='labelMode'
      :label-location='labelLocation'
  >
    <DxGroupItem>
      <DxSimpleItem
          editorType='dxTextBox'
          :editorOptions='filterInputOptions'
      >
        <DxLabel text='Text'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='startDateOptions'
      >
        <DxLabel text='Start Date'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='endDateOptions'
      >
        <DxLabel text='End Date'/>
      </DxSimpleItem>
    </DxGroupItem>
  </DxForm>
</template>

<script>
import {DxForm, DxGroupItem, DxLabel, DxSimpleItem} from 'devextreme-vue/form';
import {endViewDate, startViewDate} from '@/config';

export default {
  name: 'FilterForm',
  props: [
    'onFilterValueChange',
    'onStartDateChange',
    'onEndDateChange',
  ],
  components: {
    DxForm,
    DxSimpleItem,
    DxGroupItem,
    DxLabel
  },
  data() {
    return {
      labelMode: 'outside',
      labelLocation: 'left',
      filterInputOptions: {
        placeholder: 'Filter...',
        onKeyUp: this.onFilterValueChange
      },
      startDateOptions: {
        value: startViewDate,
        onValueChanged: this.onStartDateChange
      },
      endDateOptions: {
        value: endViewDate,
        onValueChanged: this.onEndDateChange
      }
    };
  },
};
</script>

// React/src/components/FilterForm/orig_FilterForm.jsx
import React, {memo, useMemo} from 'react';
import {Form, GroupItem, SimpleItem, Label} from 'devextreme-react/form';
import {startViewDate, endViewDate} from '../../config';

const FilterForm = memo((props) => {
    const {
        onTextValueChanged,
        onStartDateChange,
        onEndDateChange
    } = props;

    const filterInputOptions = useMemo(() => ({
        placeholder: 'Filter...',
        onKeyUp: onTextValueChanged
    }), [onTextValueChanged]);

    const startDateOptions = useMemo(() => ({
        onValueChanged: onStartDateChange,
        type: 'date',
        value: startViewDate
    }), [onStartDateChange]);

    const endDateOptions = useMemo(() => ({
        onValueChanged: onEndDateChange,
        type: 'date',
        value: endViewDate
    }), [onEndDateChange]);

    return (
        <Form>
            <GroupItem>
                <SimpleItem
                    editorType='dxTextBox'
                    editorOptions={filterInputOptions}
                >
                    <Label text='Text'/>
                </SimpleItem>
                <SimpleItem
                    editorType='dxDateBox'
                    editorOptions={startDateOptions}
                >
                    <Label text='Start Date'/>
                </SimpleItem>
                <SimpleItem
                    editorType='dxDateBox'
                    editorOptions={endDateOptions}
                >
                    <Label text='End Date'/>
                </SimpleItem>
            </GroupItem>
        </Form>
    )
});

export default FilterForm;
