// Angular/src/app/components/data-grid-remote-data/data-grid-remote-data.component.ts
import { Component, Input } from '@angular/core';
import { KeyValue } from '@angular/common';
import dxDataGrid, { RowDraggingStartEvent, RowDraggingChangeEvent, RowDraggingReorderEvent, Column } from 'devextreme/ui/data_grid';
import CustomStore from 'devextreme/data/custom_store';
import { createStore } from 'devextreme-aspnet-data-nojquery';
import { Task } from 'src/app/services/grid-data.service';

@Component({
  selector: 'grid-remote-data',
  templateUrl: './data-grid-remote-data.component.html',
})
export class DataGridRemoteDataComponent {
  @Input() shouldClearSelection: boolean = false;
  updateInProgress: boolean = false;
  keyExpr: keyof Task = "ID";
  tasksStore: CustomStore;
  employeesStore: CustomStore;

  constructor() {
    const url = 'https://js.devexpress.com/Demos/Mvc/api/RowReordering';
    this.tasksStore = createStore({
      key: 'ID',
      loadUrl: `${url}/Tasks`,
      updateUrl: `${url}/UpdateTask`,
      onBeforeSend(method, ajaxOptions) {
        ajaxOptions.xhrFields = { withCredentials: true };
      },
    });

    this.employeesStore = createStore({
      key: 'ID',
      loadUrl: `${url}/Employees`,
      onBeforeSend(method, ajaxOptions) {
        ajaxOptions.xhrFields = { withCredentials: true };
      },
    });

    this.dragStart = this.dragStart.bind(this);
    this.dragChange = this.dragChange.bind(this);
    this.reorder = this.reorder.bind(this);
  }

  dragStart(e: RowDraggingStartEvent) {
    const selectedData: Task[] = e.component.getSelectedRowsData();
    e.itemData = this.getVisibleRowValues(selectedData, e.component);
    e.cancel = !this.canDrag(e);
  }
  dragChange(e: RowDraggingChangeEvent) {
    e.cancel = !this.canDrop(e);
  }
  reorder(e: RowDraggingReorderEvent) {
    e.promise = this.updateOrderIndex(e);
    if (this.shouldClearSelection)
      e.component.clearSelection();
  }

  async updateOrderIndex(e: RowDraggingReorderEvent) {
    const visibleRows = e.component.getVisibleRows();
    const newOrderIndex = visibleRows[e.toIndex].data.OrderIndex;
    const store = e.component.getDataSource().store();
    this.updateInProgress = true;
    e.component.beginCustomLoading("Loading...");
    for (let i = 0; i < e.itemData.length; i++) {
        await store.update(e.itemData[i][this.keyExpr], { OrderIndex: newOrderIndex });
    }
    e.component.refresh().then(() => {
        e.component.endCustomLoading();
        this.updateInProgress = false;
    });
  }
  canDrag(e: RowDraggingStartEvent) {
      if (this.updateInProgress) return false;
      const visibleRows = e.component.getVisibleRows();
      return visibleRows.some(r => r.isSelected && r.rowIndex === e.fromIndex);
  }
  canDrop(e: RowDraggingChangeEvent) {
      const visibleRows = e.component.getVisibleRows();
      return !visibleRows.some(r => r.isSelected && r.rowIndex === e.toIndex);
  }
  getVisibleRowValues(rowsData: Task[], grid: dxDataGrid) {
      const visbileColumns = grid.getVisibleColumns();
      const selectedData = rowsData.map((rowData: Task) => {
          const visibleValues: any = {};
          visbileColumns.forEach((column: Column) => {
            if (column.dataField)
              visibleValues[column.dataField] = this.getVisibleCellValue(column, rowData);
          });
          return visibleValues;
      });
      return selectedData;
  }
  getVisibleCellValue(column: Column, rowData: Task) {
    if (column.dataField) {
      const propKey = column.dataField as (keyof Task);
      const cellValue = rowData[propKey];
      return column.lookup && column.lookup.calculateCellValue ? column.lookup.calculateCellValue(cellValue) : cellValue;
    }
  }
  originalOrder(a: KeyValue<number, string>, b: KeyValue<number, string>): number {
    return 0
  }
}

<dx-data-grid
    [dataSource]="tasksStore"
    [remoteOperations]="true"
    [height]="480"
>
    <dxo-row-dragging
        [allowReordering]="true"
        [onDragStart]="dragStart"
        [onDragChange]="dragChange"
        [onReorder]="reorder"
        dragTemplate="dragTemplate"
    ></dxo-row-dragging>
    <div *dxTemplate="let dragData of 'dragTemplate'" class="drag-container">
        <div *ngFor="let rowData of dragData.itemData">
            <tr class="dragged-item">
                <td *ngFor="let cellValue of rowData | keyvalue: originalOrder">
                    {{cellValue.value}}
                </td>
            </tr>
        </div>
    </div>
    <dxo-selection mode="multiple"></dxo-selection>
    <dxo-sorting mode="none"></dxo-sorting>
    <dxo-scrolling mode="virtual"></dxo-scrolling>
    <dxi-column dataField="ID" [width]="55"></dxi-column>
    <dxi-column dataField="Owner" [width]="150">
        <dxo-lookup
            [dataSource]="employeesStore"
            valueExpr="ID"
            displayExpr="FullName"
        ></dxo-lookup>
    </dxi-column>
    <dxi-column dataField="AssignedEmployee" [width]="150" caption="Assignee">
        <dxo-lookup
            [dataSource]="employeesStore"
            valueExpr="ID"
            displayExpr="FullName"
        ></dxo-lookup>
    </dxi-column>
    <dxi-column dataField="Subject"></dxi-column>
</dx-data-grid>

// React/src/DataGridRemoteData.tsx
import { useCallback, useState } from 'react';
import DataGrid, { Column, RowDragging, Sorting, Selection, Lookup, Scrolling } from 'devextreme-react/data-grid';
import { GridDemoComponentProps } from './App';
import { Task } from './data';
import { DragTemplateData } from 'devextreme/ui/draggable';
import dxDataGrid, { RowDraggingStartEvent, RowDraggingChangeEvent, RowDraggingReorderEvent, Column as DxColumn } from 'devextreme/ui/data_grid';
import { createStore } from 'devextreme-aspnet-data-nojquery';
import CustomStore from 'devextreme/data/custom_store';

const keyExpr: keyof Task = "ID";
const url = 'https://js.devexpress.com/Demos/Mvc/api/RowReordering';

const tasksStore: CustomStore = createStore({
    key: 'ID',
    loadUrl: `${url}/Tasks`,
    updateUrl: `${url}/UpdateTask`,
    onBeforeSend(method, ajaxOptions) {
        ajaxOptions.xhrFields = { withCredentials: true };
    },
});
const employeesStore: CustomStore = createStore({
    key: 'ID',
    loadUrl: `${url}/Employees`,
    onBeforeSend(method, ajaxOptions) {
        ajaxOptions.xhrFields = { withCredentials: true };
    },
});

function draggedItemsRender(data: DragTemplateData) {
    const draggedItems = data.itemData.map((item: Task) => {
        const cellValues = (Object.keys(item) as (keyof Task)[]).map((key: keyof Task) =>
            <td key={item.ID.toString() + item[key]}>{item[key]}</td>
        );
        return (<tr key={"row" + item.ID} className="dragged-item">{cellValues}</tr>)
    });
    return (<table className="drag-container">
        <tbody>{draggedItems}</tbody>
    </table>);
}
function dragChange(e: RowDraggingChangeEvent) {
    e.cancel = !canDrop(e);
}
function canDrop(e: RowDraggingChangeEvent) {
    const visibleRows = e.component.getVisibleRows();
    return !visibleRows.some(r => r.isSelected && r.rowIndex === e.toIndex);
}
function getVisibleRowValues(rowsData: Task[], grid: dxDataGrid) {
    const visbileColumns = grid.getVisibleColumns();
    const selectedData = rowsData.map((rowData: Task) => {
        const visibleValues: any = {};
        visbileColumns.forEach((column: DxColumn) => {
            if (column.dataField)
                visibleValues[column.dataField] = getVisibleCellValue(column, rowData);
        });
        return visibleValues;
    });
    return selectedData;
}
function getVisibleCellValue(column: DxColumn, rowData: Task) {
    if (column.dataField) {
        const propKey = column.dataField as (keyof Task);
        const cellValue = rowData[propKey];
        return column.lookup && column.lookup.calculateCellValue ? column.lookup.calculateCellValue(cellValue) : cellValue;
    }
}

function DataGridRemoteData(props: GridDemoComponentProps) {
    const [updateInProgress, setUpdateInProgress] = useState(false);

    const canDrag = useCallback((e: RowDraggingStartEvent) => {
        if (updateInProgress) return false;
        const visibleRows = e.component.getVisibleRows();
        return visibleRows.some(r => r.isSelected && r.rowIndex === e.fromIndex);
    }, [updateInProgress]);

    const dragStart = useCallback((e: RowDraggingStartEvent) => {
        const selectedData: Task[] = e.component.getSelectedRowsData();
        e.itemData = getVisibleRowValues(selectedData, e.component);
        e.cancel = !canDrag(e);
    }, [canDrag]);

    const updateOrderIndex = useCallback(async (e: RowDraggingReorderEvent) => {
        const visibleRows = e.component.getVisibleRows();
        const newOrderIndex = visibleRows[e.toIndex].data.OrderIndex;
        const store = e.component.getDataSource().store();
        setUpdateInProgress(true);
        e.component.beginCustomLoading("Loading...");
        for (let i = 0; i < e.itemData.length; i++) {
            await store.update(e.itemData[i][keyExpr], { OrderIndex: newOrderIndex });
        }
        e.component.refresh().then(() => {
            e.component.endCustomLoading();
            setUpdateInProgress(false);
        });
    }, []);

    const reorder = useCallback((e: RowDraggingReorderEvent) => {
        e.promise = updateOrderIndex(e);
        if (props.shouldClearSelection)
            e.component.clearSelection();
    }, [props.shouldClearSelection, updateOrderIndex]);
    
    return (
        <DataGrid
            dataSource={tasksStore}
            remoteOperations={true}
            height={480}
        >
            <RowDragging
                allowReordering={true}
                dragRender={draggedItemsRender}
                onReorder={reorder}
                onDragChange={dragChange}
                onDragStart={dragStart}
            />
            <Selection mode="multiple" />
            <Sorting mode="none" />
            <Scrolling mode="virtual" />
            <Column dataField="ID" width={55} />
            <Column dataField="Owner" width={150}>
                <Lookup dataSource={employeesStore} valueExpr="ID" displayExpr="FullName" />
            </Column>
            <Column dataField="AssignedEmployee" width={150} caption="Assignee">
                <Lookup dataSource={employeesStore} valueExpr="ID" displayExpr="FullName" />
            </Column>
            <Column dataField="Subject" />
        </DataGrid>
    )
}

export default DataGridRemoteData;
