// Vue/src/components/FilterForm/FilterForm.vue
<template>
  <DxForm
      :label-mode='labelMode'
      :label-location='labelLocation'
  >
    <DxGroupItem>
      <DxSimpleItem
          editorType='dxTextBox'
          :editorOptions='filterInputOptions'
      >
        <DxLabel text='Text'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='startDateOptions'
      >
        <DxLabel text='Start Date'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxDateBox'
          :editorOptions='endDateOptions'
      >
        <DxLabel text='End Date'/>
      </DxSimpleItem>
      <DxSimpleItem
          editorType='dxCheckBox'
          :editorOptions='checkBoxOptions'
      />
    </DxGroupItem>
  </DxForm>
</template>

<script>
import {DxForm, DxGroupItem, DxLabel, DxSimpleItem} from 'devextreme-vue/form';
import {endViewDate, startViewDate} from '@/config';

export default {
  name: 'FilterForm',
  props: [
    'onFilterValueChange',
    'onCheckboxChange',
    'onStartDateChange',
    'onEndDateChange',
    'useDisable'
  ],
  components: {
    DxForm,
    DxSimpleItem,
    DxGroupItem,
    DxLabel
  },
  data() {
    return {
      labelMode: 'outside',
      labelLocation: 'left',
      filterInputOptions: {
        placeholder: 'Filter...',
        onKeyUp: this.onFilterValueChange
      },
      startDateOptions: {
        value: startViewDate,
        onValueChanged: this.onStartDateChange
      },
      endDateOptions: {
        value: endViewDate,
        onValueChanged: this.onEndDateChange
      },
      checkBoxOptions: {
        value: this.useDisable,
        text: 'Disable appointment are not filtered',
        onValueChanged: this.onCheckboxChange
      }
    };
  },
};
</script>

// Angular/src/app/components/filter-form/filter-form.component.ts
import {Component, OnInit, Output, Input, EventEmitter} from '@angular/core';
import {OptionChangedEvent} from "devextreme/ui/form";
import {startViewDate, endViewDate} from "../../config";
import {ICheckBoxOptions, IDateOptions, IFilterInputOptions} from "../custom-scheduler/config";

@Component({
  selector: 'app-filter-form',
  templateUrl: './filter-form.component.html',
  styleUrls: ['filter-form.component.css'],
})

export class FilterFormComponent implements OnInit {
  @Output() onFilterValueChange = new EventEmitter<OptionChangedEvent>();
  @Output() onCheckboxChange = new EventEmitter<OptionChangedEvent>();
  @Output() onStartDateChange = new EventEmitter<OptionChangedEvent>();
  @Output() onEndDateChange = new EventEmitter<OptionChangedEvent>();
  @Input() useDisable: boolean;

  filterInputOptions: IFilterInputOptions;
  startDateOptions: IDateOptions;
  endDateOptions: IDateOptions;
  checkBoxOptions: ICheckBoxOptions;

  ngOnInit(): void {
    this.filterInputOptions = {
      placeholder: 'Filter...',
      onKeyUp: (e: OptionChangedEvent) => this.onFilterValueChange.emit(e)
    }
    this.startDateOptions = {
      value: startViewDate,
      onValueChanged: (e: OptionChangedEvent) => this.onStartDateChange.emit(e)
    }
    this.endDateOptions = {
      value: endViewDate,
      onValueChanged: (e: OptionChangedEvent) => this.onEndDateChange.emit(e)
    }
    this.checkBoxOptions = {
      value: this.useDisable,
      text: 'Disable appointment are not filtered',
      onValueChanged: () => this.onCheckboxChange.emit()
    }
  }
}


<dx-form
  labelLocation='left'
  labelMode='outside'
>
  <dxi-item
    editorType='dxTextBox'
    [editorOptions]="filterInputOptions"
  ></dxi-item>
  <dxi-item
    editorType='dxDateBox'
    [editorOptions]="startDateOptions"
  ></dxi-item>
  <dxi-item
    editorType='dxDateBox'
    [editorOptions]="endDateOptions"
  ></dxi-item>
  <dxi-item
    editorType='dxCheckBox'
    [editorOptions]="checkBoxOptions"
  ></dxi-item>
</dx-form>
