// React/src/App.tsx
import { useCallback, useState } from 'react';
import './App.css';
import 'devextreme/dist/css/dx.material.blue.light.compact.css';
import TabPanel, { Item } from 'devextreme-react/tab-panel';
import Switch from 'devextreme-react/switch';
import { type ValueChangedEvent } from 'devextreme/ui/switch';
import DataGridLocalData from './DataGridLocalData';
import DataGridRemoteData from './DataGridRemoteData';

function App() {
  const [shouldClearSelection, setShouldClearSelection] = useState(false);

  const switchValueChanged = useCallback((e: ValueChangedEvent) => {
    setShouldClearSelection(e.value);
  }, []);

  const dataGridLocalRender = useCallback(() => <div className='tab-item-content'>
    <DataGridLocalData shouldClearSelection={shouldClearSelection}></DataGridLocalData>
  </div>, [shouldClearSelection]);

  const dataGridRemoteRender = useCallback(() => <div className='tab-item-content'>
    <DataGridRemoteData shouldClearSelection={shouldClearSelection}></DataGridRemoteData>
  </div>, [shouldClearSelection]);

  return (
    <div className="main">
      <div className="demo-header">
        <h3>DataGrid - Select multiple items and drag`n`drop</h3>
        <div id="toggle-container">
          <span>Clear selection after drop</span>
          <Switch id="clear-after-drop-switch" value={shouldClearSelection} onValueChanged={switchValueChanged}></Switch>
        </div>
      </div>
      <TabPanel>
        <Item title="Local Data" render={dataGridLocalRender}></Item>
        <Item title="Remote Data" render={dataGridRemoteRender}></Item>
      </TabPanel>
    </div>
  );
}
export class GridDemoComponentProps {
  shouldClearSelection = false;
}
export default App;

// Angular/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  clearSelectionAfterDrop = false;
}

<div class="default-style">
  <div class="demo-header">
    <h3>DataGrid - Select multiple items and drag'n'drop</h3>
    <div id="toggle-container">
      <span>Clear selection after drop</span>
      <dx-switch
        id="clear-after-drop-switch"
        [(value)]="clearSelectionAfterDrop"
      ></dx-switch>
    </div>
  </div>
  <dx-tab-panel [deferRendering]="false">
    <dxi-item title="Local Data">
      <div *dxTemplate>
        <grid-local-data
          [shouldClearSelection]="clearSelectionAfterDrop"
        ></grid-local-data>
      </div>
    </dxi-item>
    <dxi-item title="Remote Data">
      <div *dxTemplate>
        <grid-remote-data
          [shouldClearSelection]="clearSelectionAfterDrop"
        ></grid-remote-data>
      </div>
    </dxi-item>
  </dx-tab-panel>
</div>
