// Angular/src/app/components/custom-scheduler/custom-scheduler.component.ts
import {Component, Input, OnInit} from '@angular/core';
import {views, currentDate} from "./config";
import {Appointment} from "../../data";

@Component({
  selector: 'app-custom-scheduler',
  templateUrl: './custom-scheduler.component.html',
  styleUrls: ['custom-scheduler.component.css'],
})

export class CustomSchedulerComponent implements OnInit {
  @Input() dataSource: Appointment[];
  @Input() startDate: Date;
  @Input() endDate: Date;

  views = views;
  currentDate = currentDate;

  ngOnInit(): void {
  }
}

<dx-scheduler
  currentView="month"
  [dataSource]="dataSource"
  [views]="views"
  [currentDate]="currentDate"
>
</dx-scheduler>

// Vue/src/components/CustomScheduler/CustomScheduler.vue
<template>
  <DxScheduler
      :data-source='dataSource'
      :views='views'
      :current-date='currentDate'
      current-view='month'
      :width='width'
  />
</template>

<script>
import {DxScheduler} from 'devextreme-vue/scheduler';
import {
  views,
  currentDate,
} from './config';

export default {
  name: 'CustomScheduler',
  props: [
    'dataSource',
    'startDate',
    'endDate'
  ],
  components: {
    DxScheduler,
  },
  data() {
    return {
      views: views,
      currentDate: currentDate,
      width: '80%',
    };
  }
};
</script>
