// React/src/components/CustomScheduler/CustomScheduler.jsx
import React, {useEffect} from 'react';
import Scheduler from 'devextreme-react/scheduler';
import {views, currentDate} from './config';

const CustomScheduler = (props) => {
    const {
        filterValue, dataSource, startDate, endDate
    } = props;

    useEffect(() => {
        dataSource.filter([
            ['text', 'contains', filterValue],
            'and',
            ['startDate', '>=', startDate],
            'and',
            ['endDate', '<=', endDate]
        ])
        dataSource.load()
    }, [filterValue, startDate, endDate, dataSource]);

    return (<Scheduler
        dataSource={dataSource}
        views={views}
        defaultCurrentView='month'
        defaultCurrentDate={currentDate}
        width='80%'
    />);
};

export default CustomScheduler;

// Vue/src/components/CustomScheduler/CustomScheduler.vue
<template>
  <DxScheduler
      :data-source='dataSource'
      :views='views'
      :current-date='currentDate'
      current-view='month'
      :width='width'
  />
</template>

<script>
import {DxScheduler} from 'devextreme-vue/scheduler';
import {
  views,
  currentDate,
} from './config';

export default {
  name: 'CustomScheduler',
  props: [
    'dataSource',
    'startDate',
    'endDate'
  ],
  components: {
    DxScheduler,
  },
  data() {
    return {
      views: views,
      currentDate: currentDate,
      width: '80%',
    };
  }
};
</script>
