// React/src/components/CustomScheduler.jsx
import React from "react";
import Scheduler from "devextreme-react/scheduler";
import {views, currentDate, startDayHour, endDayHour, scrolling, groups, resourcesData} from "../config";

const CustomScheduler = (props) => {
    return (<Scheduler
        dataSource={props.dataSource}
        views={views}
        defaultCurrentView="Timeline"
        defaultCurrentDate={currentDate}
        startDayHour={startDayHour}
        endDayHour={endDayHour}
        cellDuration={60}
        showAllDayPanel={false}
        scrolling={scrolling}
        groups={groups}
        resources={resourcesData}
        templatesRenderAsynchronously={false}
        width='80%'
    />);
};

export default CustomScheduler;

// Vue/src/components/CustomScheduler/CustomScheduler.vue
<template>
  <DxScheduler
      :data-source='dataSource'
      :views='views'
      :current-date='currentDate'
      current-view='month'
      :width='width'
  />
</template>

<script>
import {DxScheduler} from 'devextreme-vue/scheduler';
import {
  views,
  currentDate,
} from './config';

export default {
  name: 'CustomScheduler',
  props: [
    'dataSource',
    'startDate',
    'endDate'
  ],
  components: {
    DxScheduler,
  },
  data() {
    return {
      views: views,
      currentDate: currentDate,
      width: '80%',
    };
  }
};
</script>
